# Generated by Django 5.2.15 on 2026-06-11 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pgn', models.TextField()),
                ('event', models.CharField(blank=True, max_length=200)),
                ('site', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('round', models.CharField(blank=True, max_length=50)),
                ('white', models.JSONField(default=dict)),
                ('black', models.JSONField(default=dict)),
                ('result', models.CharField(blank=True, max_length=20)),
                ('termination', models.CharField(blank=True, max_length=100)),
                ('time_control', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, default='upload', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameEval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('positions', models.JSONField(default=list)),
                ('accuracy', models.JSONField(default=dict)),
                ('estimated_elo', models.JSONField(blank=True, null=True)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eval', to='games.game')),
            ],
        ),
    ]
