# Generated by Django 5.2.15 on 2026-06-19 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='analysis_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='analysis_source',
            field=models.CharField(blank=True, choices=[('browser', 'Browser'), ('server', 'Server')], max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='platform_played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('owner', 'source', 'external_id'), name='unique_game_external_id_per_owner'),
        ),
    ]
