# Generated by Django 5.2.15 on 2026-06-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0004_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachstudentlink',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachstudentlink',
            name='platform',
            field=models.CharField(blank=True, choices=[('chesscom', 'Chess.com'), ('lichess', 'Lichess')], max_length=20),
        ),
        migrations.AddField(
            model_name='coachstudentlink',
            name='platform_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coachstudentlink',
            name='sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coachstudentlink',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coachstudentlink',
            name='sync_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('error', 'Error')], default='idle', max_length=20),
        ),
    ]
