# Generated by Django 5.2.16 on 2026-08-01 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('device', models.JSONField(blank=True, default=dict)),
                ('games_analyzed', models.PositiveIntegerField(default=0)),
                ('active_ms', models.PositiveBigIntegerField(default=0)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen',),
            },
        ),
        migrations.CreateModel(
            name='TelemetrySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_ms', models.PositiveBigIntegerField(default=0)),
                ('landing_path', models.CharField(blank=True, default='', max_length=512)),
                ('referrer', models.CharField(blank=True, default='', max_length=1024)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('route_times', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='telemetry.telemetryclient')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('ts', models.DateTimeField(db_index=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='telemetry.telemetryclient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='telemetry.telemetrysession')),
            ],
            options={
                'ordering': ('-ts',),
            },
        ),
        migrations.AddConstraint(
            model_name='telemetrysession',
            constraint=models.UniqueConstraint(fields=('client', 'session_id'), name='telemetry_session_client_session_uniq'),
        ),
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['name', 'ts'], name='telemetry_event_name_ts'),
        ),
    ]
